version: '3.7'

services:     
  mariadb:
    container_name: web-mariadb-16
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 16-WebCalculatorDb
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5036:3306"
      
  web:
    container_name: web-app-calculator-16
    hostname: app
    build: Calculator/
    ports:
      - "0.0.0.0:5016:5016"
